### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by busla** [mitchbox/generator-react-boilerplate#3]
Node v0.12.7

```
gulp dev
[09:44:12] Using gulpfile ~/Code/react-boiler/gulpfile.js
[09:44:12] Starting 'browserify'...
events.js:85
      throw er; // Unhandled 'error' event
            ^
SyntaxError: /Users/nonni/package.json: Error while parsing JSON - Unexpected end of input while parsing file: /Users/nonni/Code/react-boiler/src/app/app.js
    at Object.parse (native)
    at OptionManager.addConfig (/Users/nonni/Code/react-boiler/node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:100:62)
    at OptionManager.findConfigs (/Users/nonni/Code/react-boiler/node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:171:32)
    at OptionManager.init (/Users/nonni/Code/react-boiler/node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/nonni/Code/react-boiler/node_modules/babelify/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/nonni/Code/react-boiler/node_modules/babelify/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/nonni/Code/react-boiler/node_modules/babelify/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Stream.end (/Users/nonni/Code/react-boiler/node_modules/babelify/index.js:38:25)
    at _end (/Users/nonni/Code/react-boiler/node_modules/babelify/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/nonni/Code/react-boiler/node_modules/babelify/node_modules/through/index.js:74:5)
```

**Comment by busla** [comment]
installed nvm and used node v10.0 to get it working.
